import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ConfigureAmplifyClientSide from "@/components/ConfigureAmplify";

import Main from './main';

const inter = Inter({ subsets: ["latin"] });

import '@radix-ui/themes/styles.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigureAmplifyClientSide />
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
